#!/usr/bin/env bash
set -e
# This hook ensures that the given commit message more or less matches the
# conventional commits style https://www.conventionalcommits.org/en/v1.0.0/
log() {
local message
local logLevel="$2"
message="[$(date)][$logLevel] Commit-Msg Hook: $1"
echo "$message"
}

log "[commit][begin]message checking" "INFO"

# Check line length
LEN="$(sed -E '/# -{24} >8 -{24}/q' $1 | wc -l | cut -d' ' -f1)"

if [ "$LEN" -gt "100" ]                                      ; then
log "Commit message line longer than 100 characters" "ERROR"
exit 1
fi

# Check header format
TYPES=(
build
chore
ci
docs
feat
fix
perf
merge
refactor
revert
style
test
release
)

HEADER_PATTERN="(?:$(IFS="|"; echo "${TYPES[*]}"))(?:\(.+\))?:.+"

if ! head -n1 $1 | grep -Eq "${HEADER_PATTERN}"; then
log "Commit message header doesn't match expected pattern." "ERROR"
exit 1
fi

log "[commit][end]message checking" "INFO"
