---
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependabot", "dependabot:ecosystem=github-actions"]
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependabot", "dependabot:ecosystem=terraform"]