formatter: "markdown table"

version: ""

header-from: main.tf
footer-from: ""

sections:
  hide: []
  show: []

content: |-
  # eks-extensions

  Manages the installation and configuration of EKS extensions as self-managed components.

  ## Compatibility

  Use this module with Terraform 1.3.0+ version and EKS on AWS Cloud.
  
  ## Requirements
  
  This module depends on an existent EKS cluster and configured providers to interact with it.
  
  ## Features

  * Configures the Kubernetes storage sub-system;
  
  * Configures the Kubernetes node autoscaler.
  
  {{ .Requirements }}
  {{ .Providers }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}

output:
  file: "README.md"
  mode: replace

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
