replicaCount: 1

args:
  tlsPrivateKeyFile: /etc/snapshot-validation/tls.key
  tlsCertFile: /etc/snapshot-validation/tls.crt
  port: 8443

image:
  repository: registry.k8s.io/sig-storage/snapshot-validation-webhook
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

webhook:
  timeoutSeconds: 2
  failurePolicy: Fail

tls:
  certificateSecret: ""
  autogenerate: true
  renew: false
  certManagerIssuerRef: {}

imagePullSecrets: []
podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  create: true
  name: ""

rbac:
  create: true