formatter: "markdown table"

version: ""

header-from: main.tf
footer-from: ""

sections:
  hide: []
  show: []

content: |-
  # terraform-aws-eks

  This module creates an EKS cluster in an AWS account.

  ## Compatibility

  Use this module with Terraform 1.3.0+ version.

  ## Requirements
  
  * The CloudWatch Log Group must be unique.
  
  ## Features

  * AWS-managed nodes;
  
  * Embedded VPC and defined networking architecture;
  
  * IAM-enabled Kubernetes service accounts;
  
  * Encrypted Kubernetes secrets.
      
  ## Known points of improvement
  
  * Handle programmatic deletion of the CloudWatch Log Group if desired its removal.
  
  ## Core concepts
  
  * [What is EKS?](https://docs.aws.amazon.com/eks/index.html);
  
  * [What is Kubernetes?](https://kubernetes.io/docs/home/);
  
  * [What is a Networking Spoke?](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/hub-spoke-network-topology);
  
  * [What are the IAM Roles for Service Accounts, as known as IRSA?](https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/setting-up-enable-IAM.html);
  
  * [How to choose the best EC2 instance type for Kubernetes workers in EKS?](https://docs.aws.amazon.com/eks/latest/userguide/choosing-instance-type.html).
    
  {{ .Requirements }}
  {{ .Providers }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}

output:
  file: "README.md"
  mode: replace

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
