---
name: Tag

on:
  workflow_call:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.chglog/**'
      - '.githooks/**'
      - 'docs/**'
      - 'tests/**'
      - 'lib/**'
      - 'LICENCE'
      - '.terraform-docs.yaml'
      - '*.md'
      - '.pre-commit-config.yaml'
      - '.gitignore'
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: minor