---
name: TerraformPullRequest

on:
  workflow_dispatch:
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Configure Terraform'
        uses: hashicorp/setup-terraform@v3
      - name: 'Terraform Format'
        run: terraform fmt -check -recursive

  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Configure Terraform'
        uses: hashicorp/setup-terraform@v3
      - name: 'Terraform Init'
        run: terraform init
      - name: 'Terraform Validate'
        run: terraform validate -no-color

  terraform-docs:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: 'Update module usage docs and push any changes back to PR branch'
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          git-commit-message: "terraform-docs: Update module usage"
          git-push: "true"
          output-file: README.md
          output-method: inject
          find-dir: .

  terraform-tfsec:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Terraform security scan'
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          tfsec_args: --concise-output
          soft_fail: false
          github_token: ${{ env.GITHUB_TOKEN }}

      - name: 'Terraform pr commenter'
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
        with:
          tfsec_args: --concise-output
          github_token: ${{ env.GITHUB_TOKEN }}
  terraform-ermetic:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: Scan with Ermetic
       uses: ermetic/actions/iac/scan@v1
       with:
         api-token: ${{ secrets.ERMETIC_API_TOKEN }}
         api-url: https://eu.app.ermetic.com
