---
name: TerraformDocs

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'variables.tf'
      - 'outputs.tf'
      - 'versions.tf'
      - '**/.terraform-docs.yaml'
jobs:
  terraform-docs:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: 'Update module usage docs and push any changes back to PR branch'
        uses: terraform-docs/gh-actions@v1.1.0
        with:
          git-commit-message: "terraform-docs: Update module usage"
          git-push: "true"
          output-file: README.md
          output-method: inject
          find-dir: .